#!/usr/bin/env bash

# Get brightness
get_backlight() {
    LIGHT=$(light | sed 's/\.[0-9]*//')
	echo "${LIGHT}"
}

# Increase brightness
inc_backlight() {
    curLight=$(get_backlight);
    let "after = $curLight / 5 * 5 + 5";
    light -S $after;
}

# Decrease brightness
dec_backlight() {
    curLight=$(get_backlight);
    let "after = $curLight- 5";
    light -S $after;
}

# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
