wallpaper {
    monitor = eDP-1
    path = ~/Pictures/arts/moon.png
    fit_mode = fit
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/arts/bonaparte_before_the_sphinx.jpg
    fit_mode = fit
}
