#!/bin/sh

cd ~ || exit

export LIBVA_DRIVER_NAME=nvidia
export XDG_SESSION_TYPE=wayland

export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1

export HYPRLAND_LOG_WLR=1

export XDG_SESSION_TYPE=wayland

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=22

exec Hyprland
